<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentNHibernate" Version="3.4.1" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NHibernate" Version="5.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Orria.cs" />
    <Compile Remove="Orria.Designer.cs" />
    <Compile Remove="Logina.cs" />
    <Compile Remove="Logina.Designer.cs" />
    <Compile Remove="ChatKontrollerra.cs" />
    <Compile Remove="ChatKontrollerra.Designer.cs" />
    <Compile Remove="UiStyleHelper.cs" />
    <EmbeddedResource Remove="Orria.resx" />
    <EmbeddedResource Remove="Logina.resx" />
    <EmbeddedResource Remove="ChatKontrollerra.resx" />
  </ItemGroup>


</Project>